# Stage 1: Build the Angular application
FROM node:krypton-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm,sharing=locked \
    npm ci --no-audit --no-fund && \
    npm cache clean --force

COPY . .

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:mainline-alpine AS prod

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist/CodeClique/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
